#!/usr/bin/env bash
set -euo pipefail

# Run on NEW server as root.
# Restores state archive generated by export_server_state.sh.

if [[ $# -lt 1 ]]; then
  echo "Usage: $0 /path/to/vpn-migration-YYYYmmdd-HHMMSS.tar.gz"
  exit 1
fi

ARCHIVE="$1"
TMP_DIR="/root/vpn-migration-restore"
rm -rf "${TMP_DIR}"
mkdir -p "${TMP_DIR}"
tar -C "${TMP_DIR}" -xzf "${ARCHIVE}"

STATE_DIR="$(find "${TMP_DIR}" -maxdepth 1 -type d -name 'state-*' | head -n 1)"
if [[ -z "${STATE_DIR}" ]]; then
  echo "State directory not found in archive"
  exit 1
fi

copy_back() {
  local rel="$1"
  local src="${STATE_DIR}/${rel}"
  local dst="/${rel}"
  if [[ -e "${src}" ]]; then
    mkdir -p "$(dirname "${dst}")"
    cp -a "${src}" "${dst}"
  fi
}

copy_back etc/vpn-product/vpn-productd.env
copy_back var/lib/vpn-product/product.db
copy_back etc/x-ui/x-ui.db
copy_back etc/caddy/Caddyfile
copy_back etc/systemd/system/vpn-productd.service
copy_back etc/systemd/system/vpn-xui-runtime-sync.service
copy_back etc/systemd/system/vpn-xui-runtime-sync.timer
copy_back etc/systemd/system/vpn-xui-client-limits-sync.service
copy_back etc/systemd/system/vpn-xui-client-limits-sync.timer
copy_back usr/local/bin/vpn-productd
copy_back usr/local/bin/vpn-xui-runtime-sync.sh
copy_back usr/local/bin/sync-xui-client-limits.py

chmod 0755 /usr/local/bin/vpn-productd || true
chmod 0755 /usr/local/bin/vpn-xui-runtime-sync.sh || true
chmod 0755 /usr/local/bin/sync-xui-client-limits.py || true

# Recommended ownership for shared DB access
chgrp vpn-product /etc/x-ui /etc/x-ui/x-ui.db 2>/dev/null || true
chmod 775 /etc/x-ui 2>/dev/null || true
chmod 664 /etc/x-ui/x-ui.db 2>/dev/null || true

systemctl daemon-reload
systemctl enable --now vpn-productd || true
systemctl enable --now vpn-xui-runtime-sync.timer || true
systemctl enable --now vpn-xui-client-limits-sync.timer || true
systemctl restart x-ui caddy vpn-productd

echo "RESTORE_DONE=1"
systemctl is-active x-ui caddy vpn-productd || true
