#!/usr/bin/env bash
# Генерирует ключи Cloudflare WARP (WireGuard) и сохраняет в /etc/vpn-product/warp.env
# Требуется установленный wgcf: https://github.com/ViRb3/wgcf
#
# Usage: sudo VPN_PRODUCT_WARP_ENV_FILE=/etc/vpn-product/warp.env ./setup_warp.sh
#   --help   показать справку

set -euo pipefail

OUT="${VPN_PRODUCT_WARP_ENV_FILE:-/etc/vpn-product/warp.env}"

usage() {
  echo "Cloudflare WARP (WireGuard) key helper for Xray."
  echo "Install wgcf, then run this script as root to write ${OUT}"
  echo ""
  echo "  wgcf register && wgcf generate"
  echo "  # Copy private key and peer public key from wgcf-profile.conf into ${OUT}:"
  echo "  WARP_PRIVATE_KEY=..."
  echo "  WARP_PEER_PUBLIC_KEY=..."
}

if [[ "${1:-}" == "--help" || "${1:-}" == "-h" ]]; then
  usage
  exit 0
fi

if [[ "${EUID}" -ne 0 ]]; then
  echo "Run as root."
  exit 1
fi

mkdir -p "$(dirname "${OUT}")"

if ! command -v wgcf >/dev/null 2>&1; then
  echo "wgcf not found. Install from https://github.com/ViRb3/wgcf/releases"
  usage
  exit 1
fi

WORKDIR="$(mktemp -d)"
trap 'rm -rf "${WORKDIR}"' EXIT
cd "${WORKDIR}"

wgcf register || true
wgcf generate

if [[ ! -f wgcf-profile.conf ]]; then
  echo "wgcf did not produce wgcf-profile.conf"
  exit 1
fi

PRIV="$(grep -E '^PrivateKey' wgcf-profile.conf | awk '{print $3}')"
PEER="$(grep -E '^PublicKey' wgcf-profile.conf | head -1 | awk '{print $3}')"

if [[ -z "${PRIV}" || -z "${PEER}" ]]; then
  echo "Could not parse keys from wgcf-profile.conf"
  exit 1
fi

umask 077
cat >"${OUT}" <<EOF
# Generated by setup_warp.sh at $(date -u +%Y-%m-%dT%H:%M:%SZ)
WARP_PRIVATE_KEY=${PRIV}
WARP_PEER_PUBLIC_KEY=${PEER}
EOF

echo "[OK] wrote ${OUT}"
